services:
  php:
    build:
      context: .
      dockerfile: phpApache.Dockerfile
    container_name: 'php'
    depends_on:
      - rabbitmq
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html/

  publisher:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'publisher'
    depends_on:
      - rabbitmq
    restart: on-failure
    entrypoint: 'php publisher.php'
    ports:
      - 8081:80
    volumes:
      - .:/var/www/html/

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    restart: on-failure
    entrypoint: 'php consumer_1.php'
    ports:
      - 80
    volumes:
      - .:/var/www/html/

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    hostname: 'rabbitmq'
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    ports:
      - 5672:5672
      - 15672:15672
